#!/bin/bash

TMP_FILE="/tmp/custom_gif_tmp"
PATH_TO_RECORD=$HOME"/Videos/"
NAME=$PATH_TO_RECORD"gif-"$(date +%s)".mp4"


if [ ! -f $TMP_FILE ]
then
    touch $TMP_FILE
    size=$(xrectsel)

    var1=$(echo $size | awk -Fx '{print $1}')
    var2=$(echo $size | awk -Fx '{print $2}' | awk -F+ '{print $1}')
    var3=$(echo $size | awk -Fx '{print $2}' | awk -F+ '{print $2}')
    var4=$(echo $size | awk -Fx '{print $2}' | awk -F+ '{print $3}')

    ffmpeg -nostats -loglevel 0 -video_size $var1'x'$var2 -framerate 25 -f x11grab -i :0.0+$var3,$var4 $NAME
else
    rm $TMP_FILE
    killall ffmpeg
fi
