#!/usr/bin/python


import hashlib
import os
import shlex
import subprocess

from datetime import datetime
from pathlib import Path

IMG_SALT = os.environ['IMG_SALT']
IMG_DIR = Path(os.environ['HOME']) / '.img-bak'
IMG_DIR.mkdir(parents=True, exist_ok=True)

tmp_filename = IMG_SALT + datetime.now().strftime("%s")
hashed_filename = hashlib.sha256(tmp_filename.encode()).hexdigest()[:15]
final_filename = IMG_DIR / (hashed_filename + ".png")
to_clipboard = f"https://kapitonov.tech/img/{hashed_filename}.png"

subprocess.run(
        shlex.split(f"gnome-screenshot --area --file={final_filename}"),
        text=True, capture_output=True)
subprocess.run(shlex.split(f'scp {final_filename} kapitonov:~/.img-bak'))

os.system(f'echo -n {to_clipboard} | xclip -i -selection clipboard')
